name: mkdocs platform (workflow)
# Publish docs via GitHub Pages to https://kjellkod.github.io/g3log/
on:
  push:
    branches:
      - master 
    paths: 
      - "**.md"
      - "**.yml"
      - docs/**

      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs && pip install mkdocs-material==8.5
      - name: Build site
        run: mkdocs build
      # build according to mkdocs.yml in root directory
      - name: Deploy https://kjellkod.github.io/g3log/
        run: mkdocs gh-deploy --force
